# baseURL
@baseURL = http://localhost:3000

###
# User Login
POST {{ baseURL }}/login
Content-Type: application/json

{
    "email": "example1113434@email.com",
	"password": "password!@2"
}


###
# User Logout
POST {{ baseURL }}/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE3NDkxMDUxLCJleHAiOjE3MTgzOTEwNTF9.ENqF5D4upuqYvIvqM-c09K24uxuJnP58VsyIHok9BeQ

{
    "id": 1
}

###
# User Login
GET {{ baseURL }}/refreshToken
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE3NDk0MDg5LCJleHAiOjMwMTM0OTQwODl9.FEqxRWGD9mmQEk4dy23AR6pxMv56rOqs4zILspU6dPM

