# baseURL
@baseURL = http://localhost:3000

###
# User Signup
POST {{ baseURL }}/signup
Content-Type: application/json

{
    "email": "example@email.com",
	"password": "password#@",
    "fio": "Иван Иваныч Иванов",
    "phone": 7897897899,
    "bio": "Очень хороший менеджер"
}

###
# User Login
POST {{ baseURL }}/login
Content-Type: application/json

{
    "email": "example@email.com",
	"password": "password#@"
}

###
# User Logout
POST {{ baseURL }}/logout
Content-Type: application/json
Authorization: Bearer xxx

{
    "id": 1
}