# baseURL
@baseURL = http://localhost:3000

###
# Create Service
POST {{ baseURL }}/createService
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE3MzMxNTMyLCJleHAiOjE3MTgyMzE1MzJ9.srvTDM6PvdqJcN6c2bu4IRWURqsSMwVUWHB7KkVgRww

{
    "subdomain": "newDomain",
    "domain": "example.com",
    "userId": 1
}

###
# Update Service
PUT {{ baseURL }}/updateService
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE3MzM0MTQ1LCJleHAiOjE3MTgyMzQxNDV9.h8Go4l7xt34a7v6o9CdPY010JamJ9IqoUNP6q5IVSmk

{
    "id": 1,
    "name": "Самый лучший сервис",
    "title": "Очень хороший тайтл",
    "type": 1,
    "brand": 7,
    "description": "Какое-то там описание...",
    "personalPolice": "<p>Политика</p>",
    "url": "https://asdf.ad/dfa",
    "autoCenter": {
        "name": "Крутой автоцентр",
        "phone": 7887887878,
        "address": "Москва, Красная Площадь",
        "email": "gfrt@fg.fg",
        "timezone": "Asia/Tomsk"
    },
    "consultant": {
        "name": "Федя",
        "male": 1,
        "photo": " ",
        "description": "Хороший консультант"
    }
}

###
# Configure Service activity
PUT {{ baseURL }}/configureServiceActivity
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE3NDMyMzQ1LCJleHAiOjE3MTgzMzIzNDV9.rWHFhj7g9Id-47kdEZSnvRZ8XlmSas-5ufXMxg7gea0

{
    "id": 1,
    "active": true
}

###
# Configure Service activity
GET {{ baseURL }}/getBrands
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE3NDMyMzQ1LCJleHAiOjE3MTgzMzIzNDV9.rWHFhj7g9Id-47kdEZSnvRZ8XlmSas-5ufXMxg7gea0

{}

